### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by romank72** [patricktcoakley/iptray#1]
Hi Patrick, great little app just what i was looking for, however it does not update while running, if client obtains new address it does not change have to close and relaunch, also if there is no ip address it does not say anything, how would I add a message that says "Not Connected to Network" and make an auto update or refresh function so we dont have to relaunch the app.

Appreciate it!

**Comment by romank72** [comment]
ok so i added a "Refresh" option which works great, but another thing i noticed is if the NIC does not have an IP address the app will not launch, how can i run the app regardless of NIC status and instead display a message "not connected to network" with the option to refresh in the event network access is restored.

trayIcon.ContextMenu.MenuItems.Add("Refresh", Restart); // Add the Refresh menu item last
        }

        private void Restart(object sender, EventArgs e)
        {
            trayIcon.Visible = false;
            Application.Restart();
        }

**Comment by romank72** [comment]
nvm i just moved the "Refresh" menu item above the foreach and it does what it want now, app runs regardless of nic status, and now i can continuously restart the app to get the ip address as it changes :) 

foreach (String s in GetIPAddresses()) // Populate menu with each IP address

**Comment by patricktcoakley** [comment]
Hi Romank72,

Thanks for creating an issue. Any chance you could create a PR with the changes you want to submit so I can take a look?
